spring:
  redis:
    cluster:
      ports:
        - 6380
        - 6381
        - 6382
        - 6383
        - 6384
        - 6385
        - 6386
        - 6387
      host: 127.0.0.1
      poolConfig:
        max-total: 8
        max-idle: 8
        max-wait-millis: -1
        min-idle: 0
